name: CD

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/cd.yml'

jobs:
  deploy:
    name: Deploy to Replit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: |
          npx jest tests/frontend.test.tsx tests/backend.test.ts --ci

      - name: Build application
        run: npm run build
      
      - name: Deploy to Replit
        uses: replit/replit-deploy@v1
        with:
          token: ${{ secrets.REPLIT_DEPLOYMENT_TOKEN }}
          username: ${{ secrets.REPLIT_USERNAME }}
          repl-id: ${{ secrets.REPLIT_ID }}

  notify:
    name: Notify on deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':rocket: New deployment completed'
          SLACK_TITLE: Deployment Status
          SLACK_USERNAME: GitHub Actions
